In [1]:
import pandas as pd
import json
import glob
import numpy as np
from sqlalchemy import create_engine

In [2]:
files = glob.glob('C:\\Users\\94400\\OneDrive\\Desktop\\cricket 2026 wc analysis\\T20wc\\*.json')

In [3]:
all_matches = []
match_info = []

for i, file in enumerate(files, start=1):

    with open(file) as f:
        data = json.load(f)
    
    info = data['info']
    match_info.append({'match_type' : info['event'].get('stage','regular'),'match_date' : info['dates'][0], 'match_city' : info['city'], 'player_of_match' : info['player_of_match'][0], 'toss_winner' : info['toss']['winner'], 'toss_dcision' : info['toss']['decision'], 'match_venue' : info['venue'],'match' : (info['teams'][0] +' vs '+ info['teams'][1]), 'match_id' : i})
    
    d = pd.DataFrame(data['innings'])
    d = d.explode('overs')

    d = d[['team']].reset_index(drop=True).join(pd.json_normalize(d['overs']))

    d = d.explode('deliveries')

    d = d[['team','over']].reset_index(drop=True).join(pd.json_normalize(d['deliveries']))
    
    d = d.explode('wickets')
    
    d = d.reset_index(drop=True).join(pd.json_normalize(d['wickets']))

    # add match id
    d['match_id'] = i

    all_matches.append(d)

final_df = pd.concat(all_matches, ignore_index=True)
match_info_df = pd.DataFrame(match_info)
final_df['over'] = final_df['over'] + 1

# Building Players list Data table

In [4]:
match_info_df = match_info_df[['match_id', 'match', 'match_date', 'match_venue', 'match_type', 'match_city', 'toss_winner', 'toss_dcision', 'player_of_match']]
t20_WC_2026_all_balls = final_df[['match_id', 'team', 'over', 'batter', 'runs.batter','runs.extras', 'runs.total', 'non_striker', 'bowler', 'kind', 'extras.wides',
       'extras.legbyes', 'extras.byes', 'extras.noballs' ]]

In [5]:
t20_WC_2026_all_balls = t20_WC_2026_all_balls.reset_index()

In [6]:
h = t20_WC_2026_all_balls[['match_id','team']].drop_duplicates()
h['count'] = h.groupby('match_id').cumcount()+1
h = h.pivot(index = 'match_id', columns = 'count', values = "team")
h['match_id'] = h.index
h = h.reset_index(drop=True)
t20_WC_2026_all_balls = pd.merge(t20_WC_2026_all_balls, h, on='match_id', how='left')
def bowling_team_fun(a):
    if(a['team'] == a[1]):
        return(a[2])
    elif(a['team'] != a[1]):
        return(a[1])
t20_WC_2026_all_balls['bowling_team'] = t20_WC_2026_all_balls.apply(bowling_team_fun,axis=1)
a=[]
a.append(t20_WC_2026_all_balls[['batter','team']].drop_duplicates())
a.append(t20_WC_2026_all_balls[['bowler','bowling_team']].drop_duplicates())
player = pd.concat(a, ignore_index=True)
player = player.fillna('')
player['player'] = player['batter'] + player['bowler']
player['country'] = player['team'] + player['bowling_team']
player = player[[ 'country','player']]
player = player.sort_values('country')
#player = pd.read_csv('player_details_og.csv')

##### got players and respective countries from this code extracted them to csv
#### used ai to fill the player table with their style and type of bowling 
#### Final Player Data is saved in file player_details_og.csv

In [7]:
player = pd.read_csv('player_details_og.csv')

# ---------------------------------------------------------------------------------------------------------------

# Building Data Tables of Phase Analysis of batsmen and bowler

In [8]:
t20_WC_2026_all_balls['stage'] = np.where(t20_WC_2026_all_balls['over'] < 7,'powerplay', np.where(t20_WC_2026_all_balls['over'] > 16, 'death', 'middle'))

## Batsmen Profile Data Table

In [9]:
def bat_phase(t20_WC_2026_all_balls, stage):
    if (stage != None):
        y = t20_WC_2026_all_balls[t20_WC_2026_all_balls['stage'] == stage ]
        prefix = stage
    else: 
        y = t20_WC_2026_all_balls
        prefix = 'over_all'
    aa = y[y['extras.wides'].isna()].groupby(['batter','match_id']).agg(
    total_runs_in_match = ('runs.batter', 'sum'),
    total_balls_in_match = ('runs.batter', 'count')
    ).reset_index()
    batsmanprofile = aa.groupby('batter').agg(
    total_runs = ('total_runs_in_match', 'sum'),
    total_balls = ('total_balls_in_match', 'sum'),
    total_matches = ('batter', 'count'),
    avg = ('total_runs_in_match', 'mean')
    ).reset_index()
    batsmanprofile['total_strike_rate'] = (batsmanprofile['total_runs']/batsmanprofile['total_balls'])*100
    
    batsmanprofile = batsmanprofile.rename(columns={
    'total_runs': f'{prefix}_total_runs',
    'total_balls': f'{prefix}_total_balls',
    'total_matches': f'{prefix}_matches',
    'avg': f'{prefix}_avg',
    'total_strike_rate': f'{prefix}_strike_rate'})
    return(batsmanprofile)

In [10]:
batter_prof = bat_phase(t20_WC_2026_all_balls, None)
batter_prof_death = bat_phase(t20_WC_2026_all_balls, 'death')
batter_prof_middle = bat_phase(t20_WC_2026_all_balls, 'middle')
batter_prof_pow = bat_phase(t20_WC_2026_all_balls, 'powerplay')
batter_prof = pd.merge(batter_prof, batter_prof_death, on='batter', how='left')
batter_prof = pd.merge(batter_prof, batter_prof_middle, on='batter', how='left')
batter_prof = pd.merge(batter_prof, batter_prof_pow, on='batter', how='left')
batter_prof = batter_prof.fillna(0)
batter_prof

,batter,over_all_total_runs,over_all_total_balls,over_all_matches,over_all_avg,over_all_strike_rate,death_total_runs,death_total_balls,death_matches,death_avg,...,middle_total_runs,middle_total_balls,middle_matches,middle_avg,middle_strike_rate,powerplay_total_runs,powerplay_total_balls,powerplay_matches,powerplay_avg,powerplay_strike_rate
0,A Busing-Volschenk,20,20,1,20.000000,100.000000,0.0,0.0,0.0,0.0,...,20.0,20.0,1.0,20.000000,100.000000,0.0,0.0,0.0,0.000000,0.000000
1,A Dutt,22,16,3,7.333333,137.500000,13.0,8.0,1.0,13.0,...,9.0,8.0,2.0,4.500000,112.500000,0.0,0.0,0.0,0.000000,0.000000
2,A Sharafu,105,98,3,35.000000,107.142857,6.0,4.0,1.0,6.0,...,75.0,64.0,3.0,25.000000,117.187500,24.0,30.0,3.0,8.000000,80.000000
3,A Sharma,95,76,3,31.666667,125.000000,18.0,6.0,1.0,18.0,...,28.0,27.0,1.0,28.000000,103.703704,49.0,43.0,3.0,16.333333,113.953488
4,A Zampa,3,3,2,1.500000,100.000000,3.0,3.0,2.0,1.5,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Wasim Ali,62,61,3,20.666667,101.639344,0.0,0.0,0.0,0.0,...,59.0,52.0,3.0,19.666667,113.461538,3.0,9.0,3.0,1.000000,33.333333
235,XC Bartlett,11,9,2,5.500000,122.222222,11.0,9.0,2.0,5.5,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
236,YS Samra,127,78,3,42.333333,162.820513,21.0,12.0,1.0,21.0,...,60.0,36.0,1.0,60.000000,166.666667,46.0,30.0,3.0,15.333333,153.333333
237,ZB Lion-Cachet,41,29,3,13.666667,141.379310,22.0,13.0,2.0,11.0,...,19.0,16.0,3.0,6.333333,118.750000,0.0,0.0,0.0,0.000000,0.000000
238,ZE Green,45,51,4,11.250000,88.235294,22.0,19.0,4.0,5.5,...,23.0,32.0,4.0,5.750000,71.875000,0.0,0.0,0.0,0.000000,0.000000

## Bowler profile Data Table

In [11]:
t20_WC_2026_all_balls[['extras.legbyes','extras.byes']] = t20_WC_2026_all_balls[['extras.legbyes','extras.byes']].fillna(0)

In [12]:
def bowler_phase (t20_WC_2026_all_balls, stage):
    if (stage != None):
        y = t20_WC_2026_all_balls[t20_WC_2026_all_balls['stage'] == stage ]
        prefix = stage
    else: 
        y = t20_WC_2026_all_balls
        prefix = 'over_all'
    bb = y.groupby(['bowler','match_id']).agg(
    total_runs_in_match = ('runs.total', 'sum'),
    total_balls_in_match = ('runs.total', 'count'),
    total_wides_in_match = ('extras.wides', 'count'),
    total_noballs_in_matches = ('extras.noballs','count'),
    total_legbyruns_in_match = ('extras.legbyes', 'sum'),
    total_byesruns_mtch = ('extras.byes', 'sum'),
    total_wickets_match = ('kind', lambda x :((x.notna()) & (x != 'run out')).sum()
    )).reset_index()
    bowlerprofile = bb.groupby('bowler').agg(
    total_runs = ('total_runs_in_match', 'sum'),
    total_byes = ('total_byesruns_mtch', 'sum'),
    total_lbyes= ('total_legbyruns_in_match', 'sum'),
    total_balls = ('total_balls_in_match', 'sum'),
    total_wides = ('total_wides_in_match', 'sum'),
    total_noballs=('total_noballs_in_matches', 'sum'),
    total_wickets=('total_wickets_match', 'sum'),
    total_matches = ('bowler', 'count'),
    avg = ('total_runs_in_match', 'mean')
    ).reset_index()
    bowlerprofile['total_runs'] = bowlerprofile['total_runs'] - (bowlerprofile['total_byes']+bowlerprofile['total_lbyes'])
    bowlerprofile['total_overs'] =(bowlerprofile['total_balls'] - (bowlerprofile['total_wides']+bowlerprofile['total_noballs']))/6
    bowlerprofile['economy'] = bowlerprofile['total_runs']/bowlerprofile['total_overs']
    
    bowlerprofile = bowlerprofile.rename(columns={
    'total_runs': f'{prefix}_total_runs',
    'total_byes': f'{prefix}_total_byes',
    'total_lbyes': f'{prefix}_total_lbyes',
    'total_balls': f'{prefix}_total_balls',
    'total_wides': f'{prefix}_total_wides',
    'total_noballs': f'{prefix}_total_noballs',
    'total_wickets': f'{prefix}_total_wickets',
    'total_matches': f'{prefix}_matches',
    'avg': f'{prefix}_avg',
    'total_overs': f'{prefix}_overs',
    'economy': f'{prefix}_economy'})
    
    return(bowlerprofile)

In [13]:
bowler_prof = bowler_phase(t20_WC_2026_all_balls, None)
bowler_prof_death = bowler_phase(t20_WC_2026_all_balls, 'death')
bowler_prof_middle = bowler_phase(t20_WC_2026_all_balls, 'middle')
bowler_prof_pow = bowler_phase(t20_WC_2026_all_balls, 'powerplay')
bowler_prof = pd.merge(bowler_prof, bowler_prof_death, on='bowler', how='left')
bowler_prof = pd.merge(bowler_prof, bowler_prof_middle, on='bowler', how='left')
bowler_prof = pd.merge(bowler_prof, bowler_prof_pow, on='bowler', how='left')
bowler_prof = bowler_prof.fillna(0)

# ---------------------------------------------------------------------------------------------------------------

# Building wickets data table

In [14]:
wickets = t20_WC_2026_all_balls[t20_WC_2026_all_balls['kind'].notna()][['match_id','bowler','bowling_team','batter','team','kind','stage']]

# ---------------------------------------------------------------------------------------------------------------

# Building schema

1) match_info_df
2) t20_WC_2026_all_balls
3) player
4) batter_prof
5) bowler_prof
6) Wickets

In [15]:
player['player_id'] = player.index+1

In [16]:
player_map = dict(zip(player['player'],player['player_id']))

In [17]:
t20_WC_2026_all_balls['batter_id'] = t20_WC_2026_all_balls['batter'].map(player_map)
t20_WC_2026_all_balls['bowler_id'] = t20_WC_2026_all_balls['bowler'].map(player_map)
batter_prof['batter_id'] = batter_prof['batter'].map(player_map)
bowler_prof['bowler_id'] = bowler_prof['bowler'].map(player_map)
wickets['batter_id'] = wickets['batter'].map(player_map)
wickets['bowler_id'] = wickets['bowler'].map(player_map)

In [18]:
wickets

,match_id,bowler,bowling_team,batter,team,kind,stage,batter_id,bowler_id
18,1,Salman Mirza,Pakistan,MP O'Dowd,Netherlands,caught,powerplay,110,165
26,1,Mohammad Nawaz,Pakistan,M Levitt,Netherlands,caught,powerplay,109,158
49,1,Abrar Ahmed,Pakistan,CN Ackermann,Netherlands,bowled,middle,112,161
77,1,Mohammad Nawaz,Pakistan,BFW de Leede,Netherlands,caught,middle,111,158
97,1,Abrar Ahmed,Pakistan,SA Edwards,Netherlands,caught,middle,113,161
...,...,...,...,...,...,...,...,...,...
11511,49,AR Patel,India,DJ Mitchell,New Zealand,caught,middle,128,47
11531,49,JJ Bumrah,India,JDS Neesham,New Zealand,bowled,middle,130,52
11532,49,JJ Bumrah,India,MJ Henry,New Zealand,bowled,middle,131,52
11545,49,JJ Bumrah,India,MJ Santner,New Zealand,bowled,death,129,52
11554,49,Abhishek Sharma,India,JA Duffy,New Zealand,caught,death,134,41

In [19]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\94400\anaconda3\lib\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

In [20]:
engine = create_engine("postgresql://postgres:root@localhost:5432/t20wc2026")

In [21]:
player.to_sql('player', engine, if_exists='replace', index=False)
batter_prof.to_sql('batter_prof', engine, if_exists='replace', index=False)
bowler_prof.to_sql('bowler_prof', engine, if_exists='replace', index=False)
wickets.to_sql('wickets', engine, if_exists='replace', index=False)
t20_WC_2026_all_balls.to_sql('all_balls', engine, if_exists='replace', index=False)
match_info_df.to_sql('match_info', engine, if_exists='replace', index=False)

49